""" Modes of Operation """
NO_PLAYER_ERROR_MODE = -1
NORMAL_MODE = 0
PLAYLIST_MODE = 1
SEARCH_NORMAL_MODE = 2
SEARCH_PLAYLIST_MODE = 3
CONFIG_MODE = 4
SELECT_PLAYER_MODE = 5
SELECT_ENCODING_MODE = 6
REMOVE_STATION_MODE = 50
SAVE_PLAYLIST_MODE = 51
ASK_TO_SAVE_PLAYLIST_MODE = 52
MAIN_HELP_MODE = 100
PLAYLIST_HELP_MODE = 101
THEME_HELP_MODE = 102
CONFIG_HELP_MODE = 103
SELECT_PLAYER_HELP_MODE = 104
SELECT_ENCODING_HELP_MODE = 105
PLAYLIST_LOAD_ERROR_MODE = 200
PLAYLIST_RELOAD_ERROR_MODE = 201
PLAYLIST_RELOAD_CONFIRM_MODE = 202
PLAYLIST_DIRTY_RELOAD_CONFIRM_MODE = 203
PLAYLIST_SCAN_ERROR_MODE = 204
SAVE_PLAYLIST_ERROR_1_MODE = 205
SAVE_PLAYLIST_ERROR_2_MODE = 206
FOREIGN_PLAYLIST_ASK_MODE = 300
FOREIGN_PLAYLIST_MESSAGE_MODE = 301
FOREIGN_PLAYLIST_COPY_ERROR_MODE = 302
THEME_MODE = 400
NOT_IMPLEMENTED_YET_MODE = 1000


