# -*- coding: utf-8 -*-
""" Modes of Operation """
NO_PLAYER_ERROR_MODE = -1
NORMAL_MODE = 0
PLAYLIST_MODE = 1
SEARCH_NORMAL_MODE = 2
SEARCH_PLAYLIST_MODE = 3
CONFIG_MODE = 4
SELECT_PLAYER_MODE = 5
SELECT_ENCODING_MODE = 6
SELECT_PLAYLIST_MODE = 7
SELECT_STATION_MODE = 8
SELECT_STATION_ENCODING_MODE = 9
NEW_THEME_MODE = 10
EDIT_THEME_MODE = 11
REMOVE_STATION_MODE = 50
SAVE_PLAYLIST_MODE = 51
ASK_TO_SAVE_PLAYLIST_WHEN_OPENING_PLAYLIST_MODE = 52
ASK_TO_SAVE_PLAYLIST_WHEN_EXITING_MODE = 53
MAIN_HELP_MODE = 100
PLAYLIST_HELP_MODE = 101
CONFIG_HELP_MODE = 102
THEME_HELP_MODE = 103
SELECT_PLAYER_HELP_MODE = 104
SELECT_ENCODING_HELP_MODE = 105
SELECT_PLAYLIST_HELP_MODE = 106
SELECT_STATION_HELP_MODE = 107
NEW_THEME_HELP_MODE = 108
EDIT_THEME_HELP_MODE = 109
ASK_TO_CREATE_NEW_THEME_MODE = 110
# TODO: return values from opening theme
PLAYLIST_RECOVERY_ERROR_MODE = 200
PLAYLIST_NOT_FOUND_ERROR_MODE = 201
PLAYLIST_LOAD_ERROR_MODE = 202
PLAYLIST_RELOAD_ERROR_MODE = 203
PLAYLIST_RELOAD_CONFIRM_MODE = 204
PLAYLIST_DIRTY_RELOAD_CONFIRM_MODE = 205
PLAYLIST_SCAN_ERROR_MODE = 206
SAVE_PLAYLIST_ERROR_1_MODE = 207
SAVE_PLAYLIST_ERROR_2_MODE = 208
FOREIGN_PLAYLIST_ASK_MODE = 300
FOREIGN_PLAYLIST_MESSAGE_MODE = 301
FOREIGN_PLAYLIST_COPY_ERROR_MODE = 302
CONFIG_SAVE_ERROR_MODE = 303
THEME_MODE = 400
NOT_IMPLEMENTED_YET_MODE = 1000

""" Theming constants """
def FOREGROUND(): return 0
def BACKGROUND(): return 1
# for pop up window
CAPTION = 2
BORDER = 3

"""
Format of theme configuration
    Name, color_pair, foreground, background
If foreground == 0, color can be edited
If > 0, get color from list item referred to by number
Same for the background
"""
THEME_ITEMS = ( ('PyRadio URL', 2, 0, 3),
        ('Messages Border', 3, 0 ,3),
        ('Status Bar', 7, 0, 0),
        ('Stations', 5, 0 ,0),
        ('Active Station', 4, 0, 3),
        ('Normal Cursor', 6, 0, 0),
        ('Active Cursor', 9, 0, 0) )
