#!/bin/bash
[ -z "$(git status | grep 'modified:' | grep README.md)" ] || {
    echo '% PyRadio README' > tmp.md
    cat README.md >> tmp.md
    pandoc -s -t html tmp.md -o README.html || exit 1
    sed -i '/<style /a \
    html {margin: 2em;} \
    h2 {margin-top: 2.5em; border-bottom:1px solid #D6D6D6;} \
    h3 {margin-top: 2em;} \
    dl {margin: 2em;} \
    dd {margin: 1em;} \
    dt {font-weight: bold;} \
    pre { background-color: #F6F6F6; padding: 1.5em; border: 1px solid #E6E6E6;}' README.html
    sed -i -e 's/<code>//g' \
        -e 's{</code>{{g' \
        -e 's{<a href="#pyradio">pyradio</a>{[pyradio]{' \
        -e 's/<p><strong>Tip:/<p style="margin: 1.5em 4em 0 4em; text-indent: -2em;"><strong>Tip:/' \
        -e 's/<li><p>/<li>/g' \
        -e 's{</</p></li>{</li>{g' \
        -e '/h1 class="title"/d' README.html
    rm tmp.md
    git add README.html
}

