#!/bin/bash
function get_mplayer(){
    local EXISTING
    local FOUND
    local TO_USE
    echo '>>> MPlayer'
    echo -n "  Reading in file MPlayer version    ... "
    EXISTING=$(sed -n '/svn-[0-9]/p' pyradio/win.py | sed -e 's/.*svn-//' -e 's/-.*//')

    echo r${EXISTING}

    echo -n "  Reading published MPlayer versions ... "

    FOUND=$(curl -s -L 'https://sourceforge.net/projects/mplayerwin/files/MPlayer-MEncoder' 2>/dev/null | grep '<tr title' | sed -e 's/<tr title="//' -e 's/".*//'|grep -e '^r')

    if [ $? -eq 0 ]
    then
        echo "$FOUND" | sed '2,$d'
    else
        echo -e '\n  Error accessing SourceForge...'
        exit 1
    fi

    count=0
    X=$FOUND
    for n in $FOUND
    do
        if ((count == 0))
        then
            if [ r"${EXISTING}" = "$n" ]
            then
                echo "Latest MPlayer version already used..."
                return
            else
                TO_USE="${n/r/}"
                break
            fi
            ((count++))
        fi
    done

    if [ ! -z "${TO_USE}" ]
    then
        echo "Version to use: ${TO_USE}"
    fi

    echo -n "  Updating in file MPlayer version ... "
    sed -i "/MPlayer-MEncoder/s/$EXISTING/$TO_USE/g" pyradio/win.py
    echo "done"
}

function get_mpv(){
    local EXISTING
    local FOUND
    local TO_USE
    echo '>>> MPV'
    echo -n '  Reading in file MPV version ... '
    EXISTING=$(grep mpv-player-windows pyradio/win.py | grep download | grep -v latest | sed -e "s/.*'h/h/" -e "s/',//")
    EXISTING=$(basename $(dirname "$EXISTING"))
    echo "$EXISTING"

    echo -n '  Reading latest MPV version  ... '
    FOUND=$(curl -s -L https://sourceforge.net/projects/mpv-player-windows/files/64bit/ 2>/dev/null | grep '"url":"/projects' | sed 's/"url":/\n&/g'  |grep '^"url"' | sed '2,$d' | sed -e 's/"url":"//' -e 's|/","full_path":".*||')

    if [ $? -ne 0 ]
    then
        echo -e '\n  Error accessing SourceForge...'
        exit 1
    fi
    FOUND=$(basename "$FOUND")
    echo "$FOUND"

    if [ "$FOUND" != "$EXISTING" ]
    then
        echo -n "  Updating in file MPV version ... "
        sed -i "s/$EXISTING/$FOUND/" pyradio/win.py
        echo "done"
    else
        echo "Latest MPV version already used..."
    fi
}

echo "Working on pyradio/win.py"
get_mpv
get_mplayer
exit 0
